const ACTION_TYPES = {
    API_PENDING: 'API_PENDING',
    API_SUCCESS: 'API_SUCCESS',
    API_ERROR: 'API_ERROR',

    // for login 
    API_LOGIN:'API_LOGIN',
    API_LOGIN_SUCCESS: 'API_LOGIN_SUCCESS',
    API_LOGIN_ERROR: 'API_LOGIN_ERROR',
  };
  export default ACTION_TYPES;