const SHOPS_ACTION_TYPES = {
    // for GET_ALL_Shops
    API_GET_ALL_SHOPS:'API_GET_ALL_SHOPS',
    API_GET_ALL_SHOPS_SUCCESS: 'API_GET_ALL_SHOPS_SUCCESS',
    API_GET_ALL_SHOPS_ERROR: 'API_GET_ALL_SHOPS_ERROR',

  };
  export default SHOPS_ACTION_TYPES;