const USER_PROFILE_ACTION_TYPES = {
    // for UPDATE_USER_PROFILE
    API_UPDATE_USER_PROFILE:'API_UPDATE_USER_PROFILE',
    API_UPDATE_USER_PROFILE_SUCCESS: 'API_UPDATE_USER_PROFILE_SUCCESS',
    API_UPDATE_USER_PROFILE_ERROR: 'API_UPDATE_USER_PROFILE_ERROR',

    // for ADD ADDRESS 
    API_ADD_ADDRESS:'API_ADD_ADDRESS',
    API_ADD_ADDRESS_SUCCESS: 'API_ADD_ADDRESS_SUCCESS',
    API_ADD_ADDRESS_ERROR: 'API_ADD_ADDRESS_ERROR',

    // for Get All ADDRESS 
    API_GET_ALL_ADDRESS:'API_GET_ALL_ADDRESS',
    API_GET_ALL_ADDRESS_SUCCESS: 'API_GET_ALL_ADDRESS_SUCCESS',
    API_GET_ALL_ADDRESS_ERROR: 'API_GET_ALL_ADDRESS_ERROR',


  };
  export default USER_PROFILE_ACTION_TYPES;