const HELPLINE_ACTION_TYPES = {
    // for Get All FAQ
    API_GET_ALL_FAQ:'API_GET_ALL_FAQ',
    API_GET_ALL_FAQ_SUCCESS: 'API_GET_ALL_FAQ_SUCCESS',
    API_GET_ALL_FAQ_ERROR: 'API_GET_ALL_FAQ_ERROR',


  };
  export default HELPLINE_ACTION_TYPES;