const EATERY_ACTION_TYPES = {
    // for GET_BANNERS 
    API_GET_BANNERS:'API_GET_BANNERS',
    API_GET_BANNERS_SUCCESS: 'API_GET_BANNERS_SUCCESS',
    API_GET_BANNERS_ERROR: 'API_GET_BANNERS_ERROR',

    // for GET_ALL_EATERY 
    API_GET_ALL_EATERY:'API_GET_ALL_EATERY',
    API_GET_ALL_EATERY_SUCCESS: 'API_GET_ALL_EATERY_SUCCESS',
    API_GET_ALL_EATERY_ERROR: 'API_GET_ALL_EATERY_ERROR',

  };
  export default EATERY_ACTION_TYPES;