const PASTORDERS_ACTION_TYPES = {
    // for getting user data from freshshop by email ID
    API_GET_USERDATA_FRESHSHOPS:'API_GET_USERDATA_FRESHSHOPS',
    API_GET_USERDATA_FRESHSHOPS_SUCCESS: 'API_GET_USERDATA_FRESHSHOPS_SUCCESS',
    API_GET_USERDATA_FRESHSHOPS_ERROR: 'API_GET_USERDATA_FRESHSHOPS_ERROR',

    // for getting All Past Order
    API_GET_ALL_PAST_ORDERS:'API_GET_ALL_PAST_ORDERS',
    API_GET_ALL_PAST_ORDERS_SUCCESS: 'API_GET_ALL_PAST_ORDERS_SUCCESS',
    API_GET_ALL_PAST_ORDERS_ERROR: 'API_GET_ALL_PAST_ORDERS_ERROR',

    // for getting  Past Order items
    API_GET_PAST_ORDERS_ITEMS:'API_GET_PAST_ORDERS_ITEMS',
    API_GET_PAST_ORDERS_ITEMS_SUCCESS: 'API_GET_PAST_ORDERS_ITEMS_SUCCESS',
    API_GET_PAST_ORDERS_ITEMS_ERROR: 'API_GET_PAST_ORDERS_ITEMS_ERROR',

        // for getting  ALL RECEIPTS 
        API_GET_ALL_RECEIPTS:'API_GET_ALL_RECEIPTS',
        API_GET_ALL_RECEIPTS_SUCCESS: 'API_GET_ALL_RECEIPTS_SUCCESS',
        API_GET_ALL_RECEIPTS_ERROR: 'API_GET_ALL_RECEIPTS_ERROR',
  };
  export default PASTORDERS_ACTION_TYPES;