export const EateryData = [
  {
    id: 0,
    name: 'Eatery item 1, Eatery item 2... ',
    date: '06 April 2022',
    delivered: 'Web',
    items: 10,
    price: 670,
    cancelled: true,
    open: true,
    past: true,
  },
  {
    id: 1,
    name: 'Eatery item 1, Eatery item 2... ',
    date: '06 April 2022',
    delivered: 'Web',
    items: 10,
    price: 670,
    cancelled: false,
    open: true,
    past: true,
  },
  {
    id: 2,
    name: 'Eatery item 1, Eatery item 2... ',
    date: '06 April 2022',
    delivered: 'Web',
    items: 10,
    price: 670,
    cancelled: true,
    open: true,
    past: true,
  },
  {
    id: 3,
    name: 'Eatery item 1, Eatery item 2... ',
    date: '06 April 2022',
    delivered: 'Web',
    items: 10,
    price: 670,
    cancelled: false,
    open: false,
    past: true,
  },
  {
    id: 4,
    name: 'Eatery item 1, Eatery item 2... ',
    date: '06 April 2022',
    delivered: 'Web',
    items: 10,
    price: 670,
  },
  {
    id: 3,
    name: 'Eatery item 1, Eatery item 2... ',
    date: '06 April 2022',
    delivered: 'Web',
    items: 10,
    price: 670,
    cancelled: true,
    open: false,
    past: false,
  },
  {
    id: 5,
    name: 'Eatery item 1, Eatery item 2... ',
    date: '06 April 2022',
    delivered: 'Web',
    items: 10,
    price: 670,
  },
];
export const GroceryData = [
  {
    id: 0,
    name: 'Grocery item 1, Grocery item 2... ',
    date: '06 April 2022',
    delivered: 'Web',
    items: 10,
    price: 670,
    cancelled: true,
    open: true,
    past: true,
  },
  {
    id: 1,
    name: 'Grocery item 1, Grocery item 2... ',
    date: '06 April 2022',
    delivered: 'Web',
    items: 10,
    price: 670,
    cancelled: false,
    open: true,
    past: true,
  },
  {
    id: 2,
    name: 'Grocery item 1, Grocery item 2... ',
    date: '06 April 2022',
    delivered: 'Web',
    items: 10,
    price: 670,
    cancelled: true,
    open: true,
    past: true,
  },
  {
    id: 3,
    name: 'Grocery item 1, Grocery item 2... ',
    date: '06 April 2022',
    delivered: 'Web',
    items: 10,
    price: 670,
    cancelled: false,
    open: false,
    past: true,
  },
  {
    id: 4,
    name: 'Grocery item 1, Grocery item 2... ',
    date: '06 April 2022',
    delivered: 'Web',
    items: 10,
    price: 670,
  },
  {
    id: 3,
    name: 'Grocery item 1, Grocery item 2... ',
    date: '06 April 2022',
    delivered: 'Web',
    items: 10,
    price: 670,
    cancelled: true,
    open: false,
    past: false,
  },
  {
    id: 5,
    name: 'Grocery item 1, Grocery item 2... ',
    date: '06 April 2022',
    delivered: 'Web',
    items: 10,
    price: 670,
  },
];

export const BuyAgain = [
  {
    id: 0,
    name: [
      {name: 'Grocery item 1', price: 10},
      {name: 'Grocery item 2', price: 10},
      {name: 'Grocery item 3', price: 10},
      {name: 'Grocery item 4', price: 10},
      {name: 'Grocery item 5', price: 10},
      {name: 'Grocery item 6', price: 10},
      {name: 'Grocery item 7', price: 10},
      {name: 'Grocery item 8', price: 10},
      {name: 'Grocery item 9', price: 10},
      {name: 'Grocery item 10', price: 10},
    ],
    date: '06 April 2022',
    delivered: 'Web',
    items: 10,
    price: 670,
  },
  {
    id: 1,
    name: 'Grocery item 1, Grocery item 2... ',
    date: '06 April 2022',
    delivered: 'Web',
    items: 10,
    price: 670,
  },
];
