const Images = {
  splash_screen: require('../../Assets/Splash.png'),
  logo: require('../../Assets/AppLogo.png'),
  theme: require('../../Assets/Theme1.png'),
  arrow_down: require('../../Assets/ic_arrow_down.png'),
  Profile: require('../../Assets/profile.png'),
  PlaceholderMap: require('../../Assets/placeholder.png'),
  defaultAddress: require('../../Assets/defaultAddress.png'),
  loginBg: require('../../Assets/LoginBG.png'),
  SideMenuBg: require('../../Assets/Sidemenu.png'),
  checkMail: require('../../Assets/checkEmail.png'),
  GoogleMap: require('../../Assets/map.png'),
  GoogleReview: require('../../Assets/GoogleReview.jpg'),

  //Loyality Screen Images
  LoyalityCardBg: require('../../Assets/LoyalityCardBg.png'),
  LoyalityReward: require('../../Assets/loyalityReward.png'),
  SpecialOffers: require('../../Assets/SpecialOffers.png'),
  lpslider1: require('../../Assets/loyalitySlider/loyaltybanners1.png'),
  lpslider2: require('../../Assets/loyalitySlider/loyaltybanners2.png'),
  lpslider3: require('../../Assets/loyalitySlider/loyaltybanners3.png'),
  //lpslider4: require('../../Assets/loyalitySlider/image4.png'),

  //Bottom Tab Images
  homeTab: require('../../Assets/BottomTab/Home.png'),
  activeHomeTab: require('../../Assets/BottomTab/activeHome.png'),
  eateryTab: require('../../Assets/BottomTab/eatery.png'),
  activeEateryTab: require('../../Assets/BottomTab/activeEatery.png'),
  shopTab: require('../../Assets/BottomTab/shop.png'),
  activeShopTab: require('../../Assets/BottomTab/activeShop.png'),
  loyalityTab: require('../../Assets/BottomTab/loyality.png'),
  activeLoyalityTab: require('../../Assets/BottomTab/activeLoyality.png'),
  deals: require('../../Assets/BottomTab/DealsInactivenew.png'),
  activeDeals: require('../../Assets/BottomTab/DealsActivenew.png'),
  activeDealsnew: require('../../Assets/BottomTab/dollar-symbol.png'),
  dealsnew: require('../../Assets/BottomTab/dollargray.png'),
  //Slider Box Images
  slider1: require('../../Assets/Slider/image1.png'),
  slider2: require('../../Assets/Slider/image2.png'),
  slider3: require('../../Assets/Slider/image3.png'),
  slider4: require('../../Assets/Slider/TakeTour_Hurleys.jpg'),
  TopB1: require('../../Assets/Slider/Top1.png'),
  TopB2: require('../../Assets/Slider/Top2.png'),
  TopB3: require('../../Assets/Slider/Top3.png'),
  //Home Screen Images
  pasta: require('../../Assets/Home/penne-pasta.png'),
  vegetables: require('../../Assets/Home/unsplash_3nX7pythQyM.png'),
  vegatables1: require('../../Assets/Home/unsplash_TcpYjs6qF9o.png'),

  whatsOnFirstItem: require('../../Assets/Home/WhatsOnSeniors.png'),
  whatsOnSecItem: require('../../Assets/Home/delivery.png'),
  whatsOnThirdItem: require('../../Assets/Home/maketoorder.png'),
  whatsOnFourThItem: require('../../Assets/Home/gifts.jpg'),
  whatsOnfifthItem: require('../../Assets/Home/Organic.png'),


  DealsofDay1: require('../../Assets/Home/unsplash_A8Gze997X-E.png'),
  DealsofDay2: require('../../Assets/Home/unsplash_AcA8moIiD3g.png'),
  fresh1: require('../../Assets/Home/unsplash_8YBHgP0WrEo.png'),
  fresh2: require('../../Assets/Home/unsplash_fa59muUjyec.png'),
  fresh3: require('../../Assets/Home/unsplash_mkVa2hLJgnI.png'),
  fresh4: require('../../Assets/Home/unsplash_Mzy-OjtCI70.png'),
  fresh5: require('../../Assets/Home/unsplash_X8AfWPcVSAc.png'),
  Banner1: require('../../Assets/Home/banner1.png'),
  Banner2: require('../../Assets/Home/banner2.png'),

  // //Shop Screen Images
  // artisanCheese: require('../../Assets/Shop/ARTISANCHEESE.png'),//
  // babyChildParent: require('../../Assets/Shop/BABYCHILDPARENT.png'),//
  // bakery: require('../../Assets/Shop/BAKERY.png'),
  // BoarHead: require('../../Assets/Shop/BoarHead.png'),
  // boxed: require('../../Assets/Shop/boxed.png'),
  // charcuterie: require('../../Assets/Shop/CHARCUTERIEESSENTIALS.png'),
  // christmas: require('../../Assets/Shop/CHRISTMAS.png'),
  // customCakes: require('../../Assets/Shop/CUSTOMCAKES.jpg'),
  // deliMeat: require('../../Assets/Shop/DELIMEAT.png'),
  // dietaryLifeStyle: require('../../Assets/Shop/DIETARYLIFESTYLE.png'),
  // freefrom: require('../../Assets/Shop/FREEFROM.png'),
  // freshProduce: require('../../Assets/Shop/FRESHPRODUCE.png'),
  // frozen: require('../../Assets/Shop/FROZEN.png'),
  // gifts: require('../../Assets/Shop/gifts.png'),
  // goodEats: require('../../Assets/Shop/GOODEATS.png'),
  // householdLaundry: require('../../Assets/Shop/HOUSEHOLDLAUNDRY.png'),
  // hurricanes: require('../../Assets/Shop/HURRICANEMUSTHAVES.png'),
  // dairyEggs: require('../../Assets/Shop/DAIRYEGGS.png'),
  // kitchenDining: require('../../Assets/Shop/KITCHENDININGHOME.png'),
  // meatsFood: require('../../Assets/Shop/MEATSEAFOOD.png'),
  // offers: require('../../Assets/Shop/OFFERS.png'),
  // organicshop: require('../../Assets/Shop/ORGANICSHOP.png'),
  // pantry: require('../../Assets/Shop/PANTRY.png'),
  // party: require('../../Assets/Shop/party.png'),
  // pet: require('../../Assets/Shop/PETSUPPLIES.png'),
  // snacks: require('../../Assets/Shop/snacks.png'),
  // sushi: require('../../Assets/Shop/SUSHI.png'),
  // teacoffee: require('../../Assets/Shop/TEACOFFEESOFTDRINKS.png'),
  // toilhealthbeauty: require('../../Assets/Shop/TOILETRIESHEALTHBEAUTY.png'),
  // grocerynew: require('../../Assets/Shop/TOILETRIESHEALTHBEAUTY.png'),
  // bread: require('../../Assets/Shop/BREAD.png'),

  //Eatery Screen Images
  eateryimage1: require('../../Assets/Eatery/image1.png'),
  eateryimage2: require('../../Assets/Eatery/image2.png'),
  eateryimage3: require('../../Assets/Eatery/image3.png'),
  eateryimage4: require('../../Assets/Eatery/image4.png'),
  eateryimage5: require('../../Assets/Eatery/image5.png'),
  eateryimage6: require('../../Assets/Eatery/image6.png'),
  eateryimage7: require('../../Assets/Eatery/image7.png'),
  eateryimage8: require('../../Assets/Eatery/image8.png'),
  eateryimage9: require('../../Assets/Eatery/imageCB.jpeg'),
  ChefNelly: require('../../Assets/Eatery/ChefNelly.png'),
  CateringLogo: require('../../Assets/Eatery/catering_logo.png'),
  //Eatery Text
  bakerywhiteTxt: require('../../Assets/Eatery/Text/1.png'),
  deliwhiteTxt: require('../../Assets/Eatery/Text/2.png'),
  rawjuicewhiteTxt: require('../../Assets/Eatery/Text/3.png'),
  hurleyEaterywhiteTxt: require('../../Assets/Eatery/Text/4.png'),
  pizzeriawhiteTxt: require('../../Assets/Eatery/Text/5.png'),
  paniniwhiteTxt: require('../../Assets/Eatery/Text/6.png'),
  burritowhiteTxt: require('../../Assets/Eatery/Text/7.png'),
  dailygrindwhiteTxt: require('../../Assets/Eatery/Text/8.png'),
  goodEatwhiteTxt: require('../../Assets/Eatery/Text/9.png'),
  freshSushiwhiteTxt: require('../../Assets/Eatery/Text/10.png'),
};

export default Images;
